# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cd1ddb45109b0c1f9fd8e236216eca5c706e8f366d4dc525d32e5b201507e19aeb0284a15c575beda4d4cfdcee5c3e42c6d5eaa7fcdacb2691670ab9a06c24

test:
  secret_key_base: 59d8af54014d6b568aba661949f54dec23c25dcd24114bf886888401dac4afa8d97fa42e27f17f82f0af31bfdffadde49da95fb28035812a4afcfd872a808bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
